#!/usr/bin/env python
import re
import sys
import logging
import os
import signal
import time
import threading
from contextlib import closing
from psycopg2 import ProgrammingError

import openerp
from openerp.cli import server as servercli
import openerp.service.workers as workers
from openerp.modules.registry import RegistryManager
from openerp.tools import config


from openerp.addons.connector import jobrunner

if __name__ == "__main__":
    args = sys.argv[1:]
    servercli.check_root_user()
    config.parse_config(args)
    openerp.netsvc.init_logger()
    servercli.report_configuration()
    jobrunner.run()