#!/usr/bin/env python
"""
Odoo Connector jobs runner
==========================

What's this?
------------
This is an alternative to connector workers, with the goal
of resolving issues due to the polling nature of workers:
* jobs do not start immediately even if there is a free connector worker
* connector workers may starve while other workers have too many jobs enqueued

It is fully compatible with the connector mechanism and only
replaces workers.

How to use
----------
* set the following environment variables:
  - ODOO_CONNECTOR_CHANNELS=root:4 (or any other channels configuration)
* launch the script.
  ex:
  $ export ODOO_CONNECTOR_CHANNELS=root:4 
  $ python connector/openerp-connector-runner -d production
"""
import re
import sys
import logging
import os
import signal
import time
import threading
from contextlib import closing
from psycopg2 import ProgrammingError

import openerp
from openerp.cli import server as servercli
import openerp.service.workers as workers
from openerp.modules.registry import RegistryManager
from openerp.tools import config


from openerp.addons.connector import jobrunner

if __name__ == "__main__":
    args = sys.argv[1:]
    servercli.check_root_user()
    config.parse_config(args)
    openerp.netsvc.init_logger()
    servercli.report_configuration()
    jobrunner.run()