[project]
name = "odoo-addons-oca-connector"
version = "19.0.20260520.0"
dependencies = [
    "odoo-addon-component==19.0.*",
    "odoo-addon-component_event==19.0.*",
    "odoo-addon-connector==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
